config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resource :profiles, only: %i(update)
  resources :profiles, only: %i(show)
  resources :casts

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }, skip: :registrations
  devise_scope :user do
    resource :registration,
             only: %i(new create edit update),
             path: 'users',
             path_names: { new: 'sign_up' },
             controller: 'devise/registrations',
             as: :user_registration
  end

  get '/colabore', to: redirect('https://github.com/RubyCastsBrasil/RubyCastsBrasil/wiki/Contribuindo'), as: :contributing
  get '/sobre', to: redirect('https://github.com/RubyCastsBrasil/RubyCastsBrasil/wiki/Sobre-o-projeto'), as: :about

  get '/' => 'home#index', as: :users
  root to: 'home#index'
end

app/views/shared/_alerts.html.erb
<% if notice || alert  %>
<div class="alerts">
  <% if notice %>
    <div class="alert alert-success alert-dismissable">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= alert %>
    </div>
  <% end %>
</div>
<% end %>

app/views/shared/_cast_list.html.erb
<div class="row">
  <h2><%= title %></h2>
</div>
<ul class="row video-items">
  <%- casts.each do |cast| %>
  <% p cast %>
    <li class="col-md-6 video-item">
      <div class="image-box">
        <div class="image-hover"></div>
        <%= link_to cast_path(cast) do %>
          <%= image_tag youtube_image_preview(cast.url), width: "255px", height: "150px" unless cast.url.nil? %>
        <% end %>
      </div>
      <%= link_to cast_path(cast), class: 'video-description' do %>
        <h3><%= cast.name %></h3>
        <p><%= cast.description %></p>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="dedication">
          <%= image_tag 'logo-rubycasts-small.png' %>
          <span class="rubycasts-with-love">
            Ruby Casts Brasil | Feito com <3
          </span>
        </div>
      </div>
      <div class="col-md-8">
        <nav class="footer-menu">
          <ul>
            <li><%= link_to t('layouts.application.menu.about'), about_url  %></li>
            <li><%= link_to t('layouts.application.menu.contributing'), contributing_url  %></li>
            <li><a href="https://www.facebook.com/pages/Ruby-Casts-Brasil/324913441002225" class="social-bt"><%= image_tag "social-facebook-icon.png" %></a></li>
            <li><a href="https://twitter.com/rubycastsbrasil"  class="social-bt"><%= image_tag "social-twitter-icon.png" %></a></li>
            <li><a href="https://github.com/RubyCastsBrasil"  class="social-bt"><%= image_tag "social-github-icon.png" %></a></li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</footer>
<!-- /Footer -->

app/views/shared/_header.html.erb
<header class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">

  <a id="forkme" href="https://github.com/RubyCastsBrasil/RubyCastsBrasil"><img style="position: absolute; top: 0; right: 0; border: 0; z-index:800" src="https://camo.githubusercontent.com/365986a132ccd6a44c23a9169022c0b5c890c387/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f7265645f6161303030302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png"></a>

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <div class="navbar-brand">
          <%= link_to root_url, class: "logo" do %>
            <%= image_tag "logo-rubycasts.png" %>
          <% end %>
        </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to t('layouts.application.menu.screencasts'), casts_url  %></li>
        <li><%= link_to t('layouts.application.menu.about'), about_url %></li>
        <li><%= link_to t('layouts.application.menu.contributing'), contributing_url  %></li>
      </ul>
      <%= render 'shared/user_header' %>
    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</header>

app/views/shared/_user_header.html.erb
<ul class="nav navbar-nav user-options">
  <% if user_signed_in? %>
    <div class="content-profile-login-box">
      <%= link_to t('devise.sessions.new.sign_out'), destroy_user_session_path, method: :delete, class: 'bt-logout' %>
      <%= link_to t('devise.registrations.edit.update'), edit_user_registration_path, class: 'account-config' %>
      <a href="<%= profile_path(current_user)%>" class="user-profile-name"><%= current_user.profile.full_name %></a>
      <%= show_avatar %>
    </div>
  <% else %>
    <div class="content-profile-login-box">
      <%= link_to t('devise.sessions.new.sign_in'), new_user_session_path, class: 'bt-default' %>
      <%= link_to t('devise.registrations.new.sign_up'), new_user_registration_path, class: 'bt-default bt-signup ' %>
    </div>
  <% end %>
</ul>