config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resource :profiles, only: %i(update)
  resources :profiles, only: %i(show)
  resources :casts

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }, skip: :registrations
  devise_scope :user do
    resource :registration,
             only: %i(new create edit update),
             path: 'users',
             path_names: { new: 'sign_up' },
             controller: 'devise/registrations',
             as: :user_registration
  end

  get '/colabore', to: redirect('https://github.com/RubyCastsBrasil/RubyCastsBrasil/wiki/Contribuindo'), as: :contributing
  get '/sobre', to: redirect('https://github.com/RubyCastsBrasil/RubyCastsBrasil/wiki/Sobre-o-projeto'), as: :about

  get '/' => 'home#index', as: :users
  root to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @casts = CastCollection.filtered_and_limited
  end
end

app/views/home/_not_signed_in.html.erb
<div class="row">
  <div class="col-md-12">
    <h2>Screencasts de Ruby criados por brasileiros para brasileiros. huehue</h2>

    <p>RubyCasts Brasil é produzido pela comunidade brasileira de Ruby. É uma plataforma criada pela comunidade para a comunidade, de forma que todo o conteúdo seja produzido por qualquer pessoa, podendo assim contribuir com o conhecimento de iniciantes e reforçando técnias de pessoas mais experientes. Os screencasts são curtos e com foco específico, fazendo com que o aprendizado seja simples e rápido.</p>
  </div>
</div>
<div class="row">
  <div class="content-buttons">
    <%= link_to "Entrar com GitHub",user_github_omniauth_authorize_path("github"), class: "bt-github" %>
    <%= link_to "Criar uma nova conta", new_user_registration_path, class: 'bt-register' %>
  </div>
</div>

app/views/home/_signed_in.html.erb
<div class="row">
  <div class="col-md-12 welcome home-signed-in">
    <h3>Bem Vindo!</h3>
    <span>O que você deseja fazer?</span>
  </div>
</div>
<div class="row choose-box-home home-signed-in">
  <div class="col-md-4 box">
    <div class="base-content-box-option">
      <%= link_to casts_path do %>
      <div class="content-box-option show-screencast">
        <div class="header-box-option">
          Ver screencasts
          <div class="circle"></div>
        </div>
        <div class="description-box-option">
          Assista, aprenda e
          curta de montão os
          melhores screenscasts
          da internet!
        </div>
      </div>
      <% end %>
    </div>
  </div>
  <div class="col-md-4 box">
    <div class="base-content-box-option">
      <div class="coming-soon">
        Em breve! :(
      </div>
      <%= link_to new_cast_path do %>
      <div class="content-box-option submit-screencast">
        <div class="header-box-option">
          Submeter um Cast
          <div class="circle"></div>
        </div>
        <div class="description-box-option">
          Quem ensina aprende
          2 vezes! Envie seu cast e
          torne o mundo um
          lugar melhor! Sério.
        </div>
      </div>
      <% end %>
    </div>
  </div>
  <div class="col-md-4 box">
    <div class="base-content-box-option">
      <div class="coming-soon">
        Em breve! :(
      </div>
      <%= link_to 'javascript::void(0)' do %>
      <div class="content-box-option starter">
        <div class="header-box-option">
          Ser iniciado (hue)
          <div class="circle"></div>
        </div>
        <div class="description-box-option">
          Aqui a gente vai
          te passar o esquema pra
          fazer o melhor cast
          no meio de todos os casts.
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<!-- Section Register -->
<section class="board-home">
  <div class="container">
    <% if user_signed_in? %>
      <%= render 'signed_in' %>
    <% else %>
      <%= render 'not_signed_in' %>
    <% end %>
  </div>
</section>
<!-- /Section Register -->

<!-- Section Latest -->
<section class="featured latest-home">
  <div class="container">
    <%= render 'shared/cast_list', casts: @casts.most_recent, title: 'Últimos screencasts publicados' %>
  </div>
</section>
<!-- /Section Latest -->

<!-- Section Latest -->
<section class="featured most-watched-home">
  <div class="container">
    <%= render 'shared/cast_list', casts: @casts.most_viewed, title: 'Screencasts mais visualizados' %>
  </div>
</section>
<!-- /Section Latest -->