config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resource :profiles, only: %i(update)
  resources :profiles, only: %i(show)
  resources :casts

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }, skip: :registrations
  devise_scope :user do
    resource :registration,
             only: %i(new create edit update),
             path: 'users',
             path_names: { new: 'sign_up' },
             controller: 'devise/registrations',
             as: :user_registration
  end

  get '/colabore', to: redirect('https://github.com/RubyCastsBrasil/RubyCastsBrasil/wiki/Contribuindo'), as: :contributing
  get '/sobre', to: redirect('https://github.com/RubyCastsBrasil/RubyCastsBrasil/wiki/Sobre-o-projeto'), as: :about

  get '/' => 'home#index', as: :users
  root to: 'home#index'
end

app/models/cast.rb
class Cast < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :tags
  has_many :cast_transitions, dependent: :destroy

  extend FriendlyId
  friendly_id :name, use: :slugged

  scope :desc, -> { order(created_at: :desc) }
  scope :find_by_param, -> (param) { find(param) }
  scope :most_recent, -> { desc.limit(10) }
  scope :by_user, -> (user_id) { where(user_id: user_id) }

  validates_presence_of :name, :url

  auto_html_for :url do
    youtube(width: "100%", height: 550, autoplay: true)
  end

  def state_machine
    @state_machine ||= CastStateMachine.new(self, transition_class: CastTransition)
  end

  delegate :can_transition_to?, :transition_to!, :transition_to, :current_state, to: :state_machine
end

app/controllers/casts_controller.rb
class CastsController < AuthorizedController
  def index
    @casts = CastCollection.all
    respond_with(@casts)
  end

  def show
    @cast = Cast.friendly.find(params[:id])
    respond_with(@cast)
  end
  def create
    @cast = current_user.casts.new(cast_params)
    @cast.save
    respond_with(@cast)
  end

  def edit
    @cast = current_user.casts.find(params[:id])
    respond_with(@cast)
  end

  def update
    @cast = current_user.casts.find_by_param(params[:id])
    @cast.update(cast_params)
    respond_with(@cast)
  end

  protected

  def cast_params
    params.require(:cast).permit(:name, :description, :notes, :url)
  end
end

app/views/casts/edit.html.erb
<div class="col-sm-6 col-md-offset-3">
	<div class="page-header">
    	<h2><%= t('.title') %></h2>
  	</div>

	<%= simple_form_for(@cast) do |f| %>
	 	<%= f.input :name %>
		<%= f.input :url %>
    <%= f.input :description, as: :text%>
		<%= f.input :notes, as: :text%>

		<%= f.button :submit, t('.update'), class: 'btn-primary pull-right' %>	
	<% end %>
</div>

app/views/casts/index.html.erb
<div class="sub-header">
  <div class="container">
    <div class="row">

      <h2 class="featured-page-title"><span>Screencasts</span> publicados</h2>
<!--       <div class="sub-menu">
        <a href="#">Mais curtidos</a>
        <a href="#">Data</a>
      </div>
      <div class="content-search">
        <form>
          <input type="text" placeholder="Buscar casts">
          <input type="submit">
        </form>
      </div> -->

    </div>
  </div>
</div>

<section class="screencasts-content-list clearfix">
  <div class="container">

    <%- @casts.all.each do |cast| %>
      <div class="row screencast-item">
        <%= link_to cast_path(cast) do %>
          <div class="content-screencast-image">
            <div class="image-hover"></div>
            <%= image_tag youtube_image_preview(cast.url), width: "255px", height: "150px" %>
          </div>
          <span class="screencast-date">
            Adicionado em <%= cast.created_at.strftime("%d/%m/%Y")%>
          </span>
          <h3><%= cast.name %></h3>
          <p>
            <%= cast.description %>
            <!-- <span class="time-count">
              Duração: 23 minutos
            </span> -->
          </p>
        <% end %>
      </div>
    <% end %>
  </div>
</section>

app/views/casts/new.html.erb
<section class="new-cast">
  <div class="container">
  
  	<% if flash[:notice] %>
		  <div class="col-md-12">
		  		<%= flash[:notice] %>
		  </div>
	  <% end %>
  
    <div class="col-md-12">
      <%= form_for @cast do |f| %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><%= t('.title') %></h3>
          </div>
          <div class="panel-body personal-data">
              <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, placeholder: 'Nome da Screencast', class: 'form-control' %>
              </div>

              <div class="form-group">
                <%= f.label :url %>
                <%= f.text_field :url, placeholder: 'URL da Screencast', class: 'form-control' %>
              </div>

              <div class="form-group">
                <%= f.label :description %>
                <%= f.text_area :description, placeholder: 'Descreva sobre o que se trata o screencast', class: 'form-control' %>
              </div>

              <div class="form-group">
                <%= f.label :notes %>
                <%= f.text_area :notes, placeholder: 'Notas do screencast, você pode usar Mardown aqui!!', class: 'form-control' %>
              </div>

          </div>
          <div class="panel-footer text-right">
              <%= f.submit t('.create'), class: 'btn btn-success' %>
          </div>
        </div>
      <% end %>
    </div>

	</div>
</section>

app/views/casts/show.html.erb
<div class="screencast-header container">
  <div class="row">
    <div class="col-md-12">
      <%= link_to("Ver todos os screencasts", casts_path, class: "show-all") %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row featured-video-player">
    <div class="col-md-12">
      <%= @cast.url_html %>
    </div>
  </div>

  <div class="video-description row">
    <div class="col-md-12">
      <h2 class="title"><%= @cast.name %></h2>
      <span class="time-info"> <%= @cast.created_at.strftime("%d/%m/%Y")%>| Autor: <%= link_to @cast.user.profile.full_name, profile_path(@cast.user)%>
<!--       <ul class="tags">
        <li><span class="glyphicon glyphicon-tag" aria-hidden="true"> </span></li>
        <li><a href="#">Ruby</a>,</li>
        <li><a href="#">Iniciante</a>,</li>
        <li><a href="#">Básico</a></li>
      </ul> -->
    </div>
  </div>
  <div class="video-text row">
    <div class="col-md-12">
      <div role="tabpanel">

        <!-- Nav tabs -->
        <ul id="myTab" class="nav nav-tabs" role="tablist">
          <li role="presentation" class="active">
            <a href="#notas" aria-controls="notas" role="tab" data-toggle="tab"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Notas do Autor</a>
            </li>
          <li role="presentation">
            <a href="#comments" aria-controls="comments" role="tab" data-toggle="tab"><span class="glyphicon glyphicon-comment" aria-hidden="true"></span> Comentários</a>
          </li>
<!--           <li role="presentation" class="pull-right">
            <a href="#others-screencasts" aria-controls="others-screencasts" role="tab" data-toggle="tab">Screencasts Similares</a>
          </li> -->
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="notas">
            <p><% p @cast %></p>
            <p><%= markdown(@cast.notes) %></p>
          </div>
          <div role="tabpanel" class="tab-pane" id="comments">
            <div id="disqus_thread"></div>
            <script type="text/javascript">
                /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
                var disqus_shortname = 'rubycastsbrasil'; // required: replace example with your forum shortname

                /* * * DON'T EDIT BELOW THIS LINE * * */
                (function() {
                    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                })();
            </script>

          </div>
          <div role="tabpanel" class="tab-pane" id="others-screencasts">
            <p>others screencasts here</p>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>